version: "3.9"
services:
  db:
    image: postgres:14
    container_name: fairhouse-db
    restart: always
    environment:
      POSTGRES_USER: fairhouse
      POSTGRES_PASSWORD: fairpass
      POSTGRES_DB: fairhouse
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
